import { Share } from 'react-native'
import type { ScanHistoryEntry } from '../types/index'

function formatDate(iso: string): string {
  const d = new Date(iso)
  return (
    d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) +
    ', ' +
    d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
  )
}

function scoreLabel(score: number): string {
  if (score >= 8) return 'Secure'
  if (score >= 5) return 'Moderate'
  return 'At Risk'
}

export async function shareReport(entry: ScanHistoryEntry): Promise<void> {
  const divider = '─'.repeat(33)
  const lines: string[] = [
    divider,
    'NetworkAudit Report',
    `Scanned: ${formatDate(entry.scannedAt)}`,
    `Network: ${entry.ssid ?? 'Unknown Network'}`,
    `Risk Score: ${entry.overallScore.toFixed(1)} / 10 — ${scoreLabel(entry.overallScore)}`,
    divider,
    `FINDINGS (${entry.findings.length})`,
    '',
  ]

  for (const f of entry.findings) {
    lines.push(`[${f.severity}] ${f.title} (CVSS ${f.cvssScore.toFixed(1)})`)
    lines.push(f.description)
    lines.push(`→ ${f.remediation}`)
    if (f.cveIds && f.cveIds.length > 0) {
      lines.push(f.cveIds.join(', '))
    }
    lines.push('')
  }

  lines.push(divider)
  lines.push('Generated by NetworkAudit — github.com/brownjesus/networkaudit')
  lines.push(divider)

  await Share.share({
    message: lines.join('\n'),
    title: 'NetworkAudit Report',
  })
}
